# Generated by Django 3.1 on 2020-09-26 03:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0002_auto_20200915_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='study_materail_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 9, 26)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='study_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
