# Generated by Django 3.1 on 2020-09-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0004_auto_20200927_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='class_name',
            field=models.CharField(choices=[('fy bcs', 'fy bcs'), ('sy bcs', 'sy bcs'), ('ty bcs', 'ty bcs')], default='fy bcs', max_length=20),
            preserve_default=False,
        ),
    ]
