# Generated by Django 3.0.5 on 2020-10-02 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0006_auto_20201001_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='study_material_time',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 2)),
        ),
    ]
