# Generated by Django 3.0.5 on 2020-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0009_auto_20201002_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='notice_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='notice_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
