# Generated by Django 3.0.5 on 2020-10-13 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0011_auto_20201002_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 13)),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='study_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
