# Generated by Django 3.0.5 on 2020-10-14 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0012_auto_20201013_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_material',
            name='study_file',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 14)),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='study_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
