# Generated by Django 3.0.5 on 2020-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0013_auto_20201014_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_material',
            name='study_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
