# Generated by Django 3.0.5 on 2020-10-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0015_auto_20201015_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_query',
            name='query_description',
            field=models.TextField(),
        ),
    ]
