# Generated by Django 3.0.5 on 2020-10-21 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0018_auto_20201015_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice_board',
            name='notice_department',
            field=models.CharField(blank=True, choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='study_material',
            name='department_name',
            field=models.CharField(blank=True, choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='department_name',
            field=models.CharField(blank=True, choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 21)),
        ),
        migrations.AlterField(
            model_name='notice_board',
            name='notice_class',
            field=models.CharField(choices=[('All', 'All '), ('FY ', 'FY '), ('SY ', 'SY '), ('TY ', 'TY ')], max_length=25),
        ),
        migrations.AlterField(
            model_name='students',
            name='class_name',
            field=models.CharField(choices=[('All', 'All '), ('FY ', 'FY '), ('SY ', 'SY '), ('TY ', 'TY ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='department_name',
            field=models.CharField(blank=True, choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='class_name',
            field=models.CharField(choices=[('All', 'All '), ('FY ', 'FY '), ('SY ', 'SY '), ('TY ', 'TY ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='class_name',
            field=models.CharField(choices=[('All', 'All '), ('FY ', 'FY '), ('SY ', 'SY '), ('TY ', 'TY ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='department_name',
            field=models.CharField(choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=20),
        ),
    ]
