# Generated by Django 3.0.5 on 2020-10-22 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0019_auto_20201021_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_teacher',
            name='department_name',
            field=models.CharField(blank=True, choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 10, 22)),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='department_name',
            field=models.CharField(blank=True, choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=20, null=True),
        ),
    ]
