# Generated by Django 3.0.5 on 2020-10-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0020_auto_20201022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_board',
            name='notice_class',
            field=models.CharField(choices=[('All', 'All'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=25),
        ),
        migrations.AlterField(
            model_name='students',
            name='class_name',
            field=models.CharField(choices=[('All', 'All'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='study_material',
            name='class_name',
            field=models.CharField(choices=[('All', 'All'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='class_name',
            field=models.CharField(choices=[('All', 'All'), ('FY', 'FY'), ('SY', 'SY'), ('TY', 'TY')], max_length=20),
        ),
    ]
