# Generated by Django 3.0.5 on 2020-10-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0021_auto_20201022_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_teacher',
            name='department_name',
            field=models.CharField(choices=[('Bsc', 'Bsc'), ('Bsc Computer Science', 'Bsc Computer Science'), ('BA', 'BA'), ('MA', 'MA'), ('Msc', 'Msc'), ('Mcs', 'Mcs')], max_length=20),
        ),
    ]
