# Generated by Django 3.0.5 on 2020-11-21 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0024_auto_20201118_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 22)),
        ),
        migrations.CreateModel(
            name='Teacher_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lect_start_time', models.TimeField(blank=True)),
                ('lect_end_time', models.TimeField(blank=True)),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.Subjects')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.Subject_Teacher')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.Teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.Students')),
                ('teacher_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bcs.Teacher_Attendance')),
            ],
        ),
    ]
