# Generated by Django 3.0.5 on 2020-11-24 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcs', '0025_auto_20201122_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 11, 24)),
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='lect_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher_attendance',
            name='lect_start_time',
            field=models.TimeField(null=True),
        ),
    ]
